import { createContext, useState, useMemo } from 'react'
import randomColor from "randomcolor";

const SKUColorMapContext = createContext();

const skuDescList = [
    "DRIP TRAY B140",
    "VALVE CHECK DUAL FLOW B3000",
    "FILTER VALVE INLET B3000",
    "CHUTE B3000 CABINET",
    "ASM HWT SPARE B3000",
    "ASM DRIP TRAY B3000",
    "B3000SE CONTROL PANEL",
    "ASM BASE PLATE B3000",
    "ASM COIN MECH LOCK SET SPARE B3000",
    "ASM DRIP TRAY SPARE B130",
    "ASM HOLDER PIVOT K CUP SPARE B3000",
    "ASM HOLDER KCUP W/FUNNEL SPARE",
    "ASM PLATE HOUSING UPPER SPARE B3000",
    "ASM DRIP TRAY AND PLATE B200",
    "ASM HOLDER KCUP SPARE B130/140/145/",
    "CWT / COVER POUR OVER B150/155",
    "DRIP TRAY AND PLATE B140",
    "SPARE CABLE, COIN CHANGER B3000",
    "ASM SPARE COLD WATER TANK W/LID V12",
    "COLD WATER TANK SPARE K15X",
    "COLD WATER TANK FLOAT SPARE K15X",
    "PUNCTURE MECHANISM PLATE SPARE K15X",
    "BOLT RIGHT SIDE PANEL",
    "ASM BOLT BREW AIR PUMP",
    "BOLT DRIP TRAY PLATE",
    "BRWR SKIN K10 UNIVERSITY OF TX",
    "KEUR VUE WIRE RACK",
    "KEUR CABINET B3000",
    "DRIP TRAY NEW AIRPOT RACK 2PK 25/CS",
    "CUP GMCR IP PAPER 12OZ 1000UN",
    "LID DOME GMCR PLA COLD 1000UN",
    "KCUP DSHP COCONUT MOCHA CBT",
    "DESCALE BULK 12UN",
    "KEUR KCUP SS TRAVEL MUG WL 14OZ",
    "KEUR RINSE CUP 10CT E/F",
    "MSTR CTN 72PK 8CT",
    "ASM CWT SPARE KCMPT",
    "TULL FR RST GR 12OZ FSB",
    "GMCR DK MAGIC GR 12OZ FSB",
    "GMCR BKFST BL GR 12OZ FSB",
    "DIVIDER DPLY FL/PAL A 48CT CTN 180U",
    "KEUR BRWR KMINI OASIS RFSH",
    "KEUR SHORT RESERVOIR WFSK RFSH",
    "KEUR NONROLLING STORAGE DRAWER SM R",
    "SIDE SHELF DPLY 352UN FL/PAL R1",
    "KEUR BRWR KCAFE SPEC ED NICKEL",
    "TRAY DPLY SWIS KCUP HT CHOC 12CT 28",
    "GMCR KCUP PMPK SP FS 18CT '19",
    "GMCR FRAC FT COLOMB SLECT GR 2.2OZ",
    "ASM BRW VLV BRWR K4000",
    "NUT SCREW SPR BRWR K4000",
    "NOZZLE COVER BRWR K4000",
    "LEFT SOLUBLE CONV BRWR K4000",
    "INLET VALVE BRWR K4000",
    "PWR AUG MTR BRWR K4000",
    "TOUCH DPLY MN PCB BRWR K4000",
    "RIGHT SOLUBLE CONV BRWR K4000",
    "ASM DRIP TRAY BRWR K1500",
    "ASM CWT BRWR K1500",
    "KEUR BRWR KCLSC BLK G2",
    "DPLY GMCR BAG VARI V2 36UN",
    "RKCPP GMCR KCUP DK MAGIC XB 24CT",
    "RKCPP GMCR KCUP FR VAN DECAF 24CT",
    "RKCPP GMCR KCUP DK MAGIC XB N 12CT",
    "RKCPP DSHP KCUP DNT SHOP N 12CT",
    "RKCPP GMCR KCUP BKFST BL 12CT",
    "RKCPP DSHP KCUP DNT SHOP DEC N 12CT",
    "RKCPP GMCR KCUP CRML VAN CRM N 12CT",
    "RKCPP GMCR KCUP FR VAN N 12CT",
    "RKCPP GMCR KCUP BKFST BL DEC 12CT",
    "RKCPP GMCR KCUP HALF-CAFF N 12CT",
    "RKCPP KEUR RINSE CUP 10CT E/F",
    "RKCPP GMCR KCUP BKFST BL 18CT 4/CS",
    "RKCPP KRGR KCUP COLOMB 48CT AUTO",
    "RKCPP GMCR KCUP BKFST BL 32CT",
    "KEUR BRWR K1500 192CT MED BUNDLE",
    "CORR DPLY BAG PDQ 2/CS R1",
    "DSHP KCUP MOCHA LATTE 10CT RKCPP",
    "KEUR ACC COFF STATION",
    "SWIS KCUP MILK CHOC 10CT RKC R1",
    "SWIS KCUP MILK CHOC 22CT SLIM RKC R",
    "HUTCH RT SIDE HPAL KMINI/32CT 64UN",
    "GMCR FRAC RS OUR BL 2.2OZ 100UN",
    "RKCPP KRKR KCUP CLAS 12CT",
    "KTD KCUP GMCR BKFST BL RKCPP 400/CS",
    "KTD KCUP GTVL COLOMB RKCPP 400/CS",
    "DW DRINKMAKER KIT PROP65",
    "ASM CWP K3500",
    "ASM CWT K3500",
    "ASM HWT K3500",
    "KEUR ACC KDUO 3MO BRWR MAINTENANCE",
    "RKCPP GMCR KCUP RS NANT BL 32CT",
    "RKCPP GMCR KCUP RS NANT BL 12CT",
    "RKCPP KRGR KCUP COLOMBIAN 96CT",
    "DSHP KCUP REG 48CT HR RKCPP",
    "BX LITHO KEUR KCUP VARI SAMS 72CT R",
    "GMCR KCUP BRKFST BL 60CT RKC",
    "MCAF KCUP PRM RST DECAF 12CT RKC",
    "MCAF KCUP BKFST BL 12CT RKC",
    "MCAF KCUP PRM RST DECAF 32CT RKC",
    "MCAF KCUP PRM RST 84CT RKC",
    "MCAF KCUP PRM RST 48CT RKC HR",
    "ASM DRIP TRAY K2500",
    "KTD KCUP GTVL HOT CHOC RKC 400/CS",
    "AFH CLNG KIT B2CUP",
    "DPLY KEUR BRWR MINIB MIXED AH GROC"
];

const getSkuDescColorMap = () => {
    let skuDescColorMap = {}
    skuDescList.forEach(skuDesc => {
        skuDescColorMap[skuDesc] = randomColor({
            luminosity: 'dark',
            alpha: 5
        })
    })
    return skuDescColorMap
}

export const SKUColorMapProvider = ({ children }) => {
    const [changeColor, setChangeColor] = useState(true);

    const skuDescColorMap = useMemo(() => getSkuDescColorMap(), [changeColor]);

    const value = { setChangeColor, skuDescColorMap }
    return (
        <SKUColorMapContext.Provider value={value}>
            {children}
        </SKUColorMapContext.Provider>
    )
}
export default SKUColorMapContext;